### PR TITLE
Add de-dotting support for ES 2.x

### LINKED ISSUE #11: ES 2.x support
With ES 2.x field names can no longer contain dots - also see:

https://github.com/looplab/logspout-logstash/issues/11
https://github.com/elastic/elasticsearch/issues/14594

When using e.g. Rancher, which heavily uses labels with dots, logspout-redis-logstash totally breaks down on a Rancher host.

Unfortunately I don't know Go that well, so I can't create a PR :-(

### PR DESCRIPTION
**Pull request by adepretis**
Fixes #11:
- adds dedot_labels parameter
- replaces all Docker labels "." with "_"

### CODE REVIEW

**Comment by adepretis** [comment]
I added some tests, but don't know how to run them (e.g. using `build-dev.sh`). Maybe you could update the `README.md` to include that information.

**Comment by adepretis** [comment]
@rtoma any comments?

**Comment by rtoma** [comment]
thanks you so much!

**Comment by adepretis** [comment]
Great, thanks for the merge! Would it be possible to update https://hub.docker.com/r/rtoma/logspout-redis-logstash/ to 0.1.7 too?

**Comment by rtoma** [comment]
I was already working on it, but upstream stuff broke. I need a 0.1.7 image myself, so you get one on hub soon.

**Comment by rtoma** [comment]
Hub has been updated with 0.1.7 and 0.1.8 (for new buildsystem, try it out!)

**Comment by adepretis** [comment]
Great work with the new buildsystem - thank you!

**Pull request merged**
