### PR TITLE
Added support for docker labels

### PR DESCRIPTION
**Pull request by teemupo**

### CODE REVIEW

**Comment by rtoma** [comment]
Hi @teemupo, thank you for your pull request.

To quote https://docs.docker.com/engine/userguide/labels-custom-metadata/:

> Note: Support for daemon-labels was added in Docker 1.4.1. Labels on containers and images are new in Docker 1.6.0

I am wondering if your code will break on such old Docker servers. Do you have any idea?

**Comment by teemupo** [comment]
It might break on Docker servers older than 1.6. Was going to test it, but didn't find such an old version easily anywhere. And versions that old are quite useless anyway as Docker Hub has already deprecated them since last December.

[https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/](https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/)

**Comment by rtoma** [comment]
Agreed. I have merged your pull request and will try to test on old Docker servers. I hope the Docker client lib we use can handle no label element compared to an empty label list.

**Comment by teemupo** [comment]
One thing came to mind. You can't even pull this image from Docker Hub with Docker version older than 1.6 anymore, so this change would possibly break things only for users who have Docker 1.5 or older and manually build the image from this repo. I guess the amount of users affected by this is quite minimal.

**Comment by rtoma** [comment]
Very good point. Thanks for sharing.

**Pull request merged**
